// Post API 定义，包含博客文章的请求和响应消息

// Copyright 2024 孔令飞 <colin404@foxmail.com>. All rights reserved.
// Use of this source code is governed by a MIT style
// license that can be found in the LICENSE file. The original repo for
// this file is https://github.com/onexstack/miniblog. The professional
// version of this repository is https://github.com/onexstack/onex.

// Code generated by protoc-gen-defaults. DO NOT EDIT.

package v1

import (
	"google.golang.org/protobuf/types/known/durationpb"
	"google.golang.org/protobuf/types/known/timestamppb"
	"google.golang.org/protobuf/types/known/wrapperspb"
)

var (
	_ *timestamppb.Timestamp
	_ *durationpb.Duration
	_ *wrapperspb.BoolValue
)

func (x *Post) Default() {
}

func (x *CreatePostRequest) Default() {
}

func (x *CreatePostResponse) Default() {
}

func (x *UpdatePostRequest) Default() {
}

func (x *UpdatePostResponse) Default() {
}

func (x *DeletePostRequest) Default() {
}

func (x *DeletePostResponse) Default() {
}

func (x *GetPostRequest) Default() {
}

func (x *GetPostResponse) Default() {
}

func (x *ListPostRequest) Default() {
}

func (x *ListPostResponse) Default() {
}
